const PHONICS_DATA = [
  { letter: 'A', examples: [{ word: 'Apple', emoji: '🍎' }, { word: 'Ant', emoji: '🐜' }, { word: 'Alligator', emoji: '🐊' }] },
  { letter: 'B', examples: [{ word: 'Ball', emoji: '⚽' }, { word: 'Bear', emoji: '🐻' }, { word: 'Butterfly', emoji: '🦋' }] },
  { letter: 'C', examples: [{ word: 'Cat', emoji: '🐱' }, { word: 'Car', emoji: '🚗' }, { word: 'Cake', emoji: '🎂' }] },
  { letter: 'D', examples: [{ word: 'Dog', emoji: '🐶' }, { word: 'Duck', emoji: '🦆' }, { word: 'Dinosaur', emoji: '🦕' }] },
  { letter: 'E', examples: [{ word: 'Elephant', emoji: '🐘' }, { word: 'Egg', emoji: '🥚' }, { word: 'Eagle', emoji: '🦅' }] },
  { letter: 'F', examples: [{ word: 'Fish', emoji: '🐟' }, { word: 'Fox', emoji: '🦊' }, { word: 'Frog', emoji: '🐸' }] },
  { letter: 'G', examples: [{ word: 'Gorilla', emoji: '🦍' }, { word: 'Grapes', emoji: '🍇' }, { word: 'Ghost', emoji: '👻' }] },
  { letter: 'H', examples: [{ word: 'Hat', emoji: '🎩' }, { word: 'Horse', emoji: '🐴' }, { word: 'Heart', emoji: '❤️' }] },
  { letter: 'I', examples: [{ word: 'Igloo', emoji: '🏠' }, { word: 'Insect', emoji: '🐛' }, { word: 'Ice', emoji: '🧊' }] },
  { letter: 'J', examples: [{ word: 'Jar', emoji: '🫙' }, { word: 'Jacket', emoji: '🧥' }, { word: 'Juice', emoji: '🧃' }] },
  { letter: 'K', examples: [{ word: 'Key', emoji: '🔑' }, { word: 'Kite', emoji: '🪁' }, { word: 'Kangaroo', emoji: '🦘' }] },
  { letter: 'L', examples: [{ word: 'Lion', emoji: '🦁' }, { word: 'Lemon', emoji: '🍋' }, { word: 'Ladybug', emoji: '🐞' }] },
  { letter: 'M', examples: [{ word: 'Monkey', emoji: '🐒' }, { word: 'Moon', emoji: '🌙' }, { word: 'Milk', emoji: '🥛' }] },
  { letter: 'N', examples: [{ word: 'Nose', emoji: '👃' }, { word: 'Nest', emoji: '🪺' }, { word: 'Nut', emoji: '🥜' }] },
  { letter: 'O', examples: [{ word: 'Orange', emoji: '🍊' }, { word: 'Owl', emoji: '🦉' }, { word: 'Octopus', emoji: '🐙' }] },
  { letter: 'P', examples: [{ word: 'Pig', emoji: '🐷' }, { word: 'Pizza', emoji: '🍕' }, { word: 'Panda', emoji: '🐼' }] },
  { letter: 'Q', examples: [{ word: 'Queen', emoji: '👸' }, { word: 'Quail', emoji: '🐦' }, { word: 'Question', emoji: '❓' }] },
  { letter: 'R', examples: [{ word: 'Rabbit', emoji: '🐰' }, { word: 'Rainbow', emoji: '🌈' }, { word: 'Robot', emoji: '🤖' }] },
  { letter: 'S', examples: [{ word: 'Sun', emoji: '☀️' }, { word: 'Snake', emoji: '🐍' }, { word: 'Star', emoji: '⭐' }] },
  { letter: 'T', examples: [{ word: 'Tiger', emoji: '🐯' }, { word: 'Train', emoji: '🚂' }, { word: 'Turtle', emoji: '🐢' }] },
  { letter: 'U', examples: [{ word: 'Umbrella', emoji: '☂️' }, { word: 'Unicorn', emoji: '🦄' }, { word: 'Up', emoji: '⬆️' }] },
  { letter: 'V', examples: [{ word: 'Violin', emoji: '🎻' }, { word: 'Volcano', emoji: '🌋' }, { word: 'Van', emoji: '🚐' }] },
  { letter: 'W', examples: [{ word: 'Whale', emoji: '🐋' }, { word: 'Wolf', emoji: '🐺' }, { word: 'Watermelon', emoji: '🍉' }] },
  { letter: 'X', examples: [{ word: 'X-ray', emoji: '🩻' }, { word: 'Xylophone', emoji: '🎵' }, { word: 'Box', emoji: '📦' }] },
  { letter: 'Y', examples: [{ word: 'Yak', emoji: '🐃' }, { word: 'Yo-yo', emoji: '🪀' }, { word: 'Yellow', emoji: '💛' }] },
  { letter: 'Z', examples: [{ word: 'Zebra', emoji: '🦓' }, { word: 'Zero', emoji: '0️⃣' }, { word: 'Zipper', emoji: '🤐' }] },
];

const WORD_MATCH_DATA = [
  { word: 'cat', emoji: '🐱' }, { word: 'dog', emoji: '🐶' }, { word: 'pig', emoji: '🐷' },
  { word: 'cow', emoji: '🐮' }, { word: 'duck', emoji: '🦆' }, { word: 'fish', emoji: '🐟' },
  { word: 'bird', emoji: '🐦' }, { word: 'frog', emoji: '🐸' }, { word: 'horse', emoji: '🐴' },
  { word: 'bear', emoji: '🐻' }, { word: 'lion', emoji: '🦁' }, { word: 'tiger', emoji: '🐯' },
  { word: 'rabbit', emoji: '🐰' }, { word: 'snake', emoji: '🐍' }, { word: 'turtle', emoji: '🐢' },
  { word: 'apple', emoji: '🍎' }, { word: 'banana', emoji: '🍌' }, { word: 'orange', emoji: '🍊' },
  { word: 'cake', emoji: '🎂' }, { word: 'pizza', emoji: '🍕' }, { word: 'bread', emoji: '🍞' },
  { word: 'egg', emoji: '🥚' }, { word: 'milk', emoji: '🥛' }, { word: 'cookie', emoji: '🍪' },
  { word: 'car', emoji: '🚗' }, { word: 'bus', emoji: '🚌' }, { word: 'train', emoji: '🚂' },
  { word: 'plane', emoji: '✈️' }, { word: 'boat', emoji: '⛵' }, { word: 'bike', emoji: '🚲' },
  { word: 'sun', emoji: '☀️' }, { word: 'moon', emoji: '🌙' }, { word: 'star', emoji: '⭐' },
  { word: 'cloud', emoji: '☁️' }, { word: 'rain', emoji: '🌧️' }, { word: 'snow', emoji: '❄️' },
  { word: 'tree', emoji: '🌳' }, { word: 'flower', emoji: '🌸' }, { word: 'book', emoji: '📚' },
  { word: 'ball', emoji: '⚽' }, { word: 'hat', emoji: '🎩' }, { word: 'key', emoji: '🔑' },
];

const SPELLING_WORDS = [
  { word: 'cat', emoji: '🐱', hint: '야옹~ 동물' },
  { word: 'dog', emoji: '🐶', hint: '멍멍~ 동물' },
  { word: 'sun', emoji: '☀️', hint: '하늘에서 빛나는 것' },
  { word: 'hat', emoji: '🎩', hint: '머리에 쓰는 것' },
  { word: 'cup', emoji: '☕', hint: '음료를 마시는 것' },
  { word: 'pig', emoji: '🐷', hint: '꿀꿀~ 농장 동물' },
  { word: 'egg', emoji: '🥚', hint: '새가 낳는 것' },
  { word: 'bug', emoji: '🐛', hint: '작은 벌레' },
  { word: 'ant', emoji: '🐜', hint: '아주 작은 곤충' },
  { word: 'bus', emoji: '🚌', hint: '여러 명이 타는 큰 차' },
  { word: 'pen', emoji: '✒️', hint: '글씨 쓸 때 쓰는 것' },
  { word: 'fox', emoji: '🦊', hint: '꾀 많은 주황색 동물' },
  { word: 'map', emoji: '🗺️', hint: '길을 찾을 때 보는 것' },
  { word: 'web', emoji: '🕸️', hint: '거미가 만드는 것' },
  { word: 'van', emoji: '🚐', hint: '가족이 타는 큰 자동차' },
  { word: 'jet', emoji: '✈️', hint: '하늘을 빠르게 나는 것' },
  { word: 'mud', emoji: '💧', hint: '비 온 뒤 젖은 흙' },
  { word: 'lid', emoji: '🍳', hint: '냄비 위에 덮는 것' },
  { word: 'net', emoji: '🥅', hint: '공을 잡는 그물' },
  { word: 'zip', emoji: '🤐', hint: '옷을 잠그는 것' },
];

const SPEAKING_WORDS = [
  { word: 'hello', emoji: '👋', translation: '안녕' },
  { word: 'apple', emoji: '🍎', translation: '사과' },
  { word: 'star', emoji: '⭐', translation: '별' },
  { word: 'bird', emoji: '🐦', translation: '새' },
  { word: 'cake', emoji: '🎂', translation: '케이크' },
  { word: 'fish', emoji: '🐟', translation: '물고기' },
  { word: 'milk', emoji: '🥛', translation: '우유' },
  { word: 'rain', emoji: '🌧️', translation: '비' },
  { word: 'tree', emoji: '🌳', translation: '나무' },
  { word: 'blue', emoji: '🔵', translation: '파란색' },
  { word: 'dog', emoji: '🐶', translation: '개' },
  { word: 'cat', emoji: '🐱', translation: '고양이' },
  { word: 'sun', emoji: '☀️', translation: '태양' },
  { word: 'moon', emoji: '🌙', translation: '달' },
  { word: 'book', emoji: '📚', translation: '책' },
  { word: 'water', emoji: '💧', translation: '물' },
  { word: 'green', emoji: '🟢', translation: '초록색' },
  { word: 'happy', emoji: '😊', translation: '행복한' },
  { word: 'jump', emoji: '🏃', translation: '점프' },
  { word: 'love', emoji: '❤️', translation: '사랑' },
];
